[project]
name = "ComfyUI_OneButtonPrompt_Flux"
description = "ComfyUI_OneButtonPrompt_Flux is a Flux prompt generation node. The subject can be "human," "other" or a combination of both. For human, pose settings can be enabled. Additionally, various styles can be applied. Finally, combine it with "Prompt Enhancement" to seamlessly automate image generation, eliminating the hassle of designing prompts."
version = "1.0.0"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/billwuhao/ComfyUI_OneButtonPrompt_Flux"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "MW"
DisplayName = "ComfyUI_OneButtonPrompt_Flux"
Icon = ""